<a href="https://colab.research.google.com/github/leesolhahaha/Data_Analysis_with_Python/blob/main/08_%5BPandas%5D_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EA%B0%80%EA%B3%B5%2C_apply%2C_map%2C_str.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv("./data/titanic_train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# apply ⭐️
- 사용자 정의 함수를 데이터에 적용할 때 사용한다.
- 레코드 단위로 사용자 정의 함수가 적용
  - apply에 들어가는 함수는 "반드시" 리턴이 있어야 한다.

apply로 사용할 수 있는 것을 for문을 사용하지 않을 것을 주의하기

데이터를 꺼내서 무언가를 하고 싶을 때

In [ ]:
# 예시. pclass가 1이고, SibSp 1이면 1, 아니면 0
#  pclass==1 and SibSp==1
def pclass_sibsp(row):
  if row['Pclass'] == 1 and row['SibSp'] == 1:
    return 1
  else:
    return 0

df1 = df.copy()

In [ ]:
df1["pclass_sibsp_filter"] = df1.apply(pclass_sibsp, axis=1) # 함수이름이 들어가면서 콜백함수형태로 넘어옴
# apply는 함수의 이름만 들어가야함
# axis=1은 적용 방향을 의미함 열 방향 중에 행데이터를 넘어가게 하는 것
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,pclass_sibsp_filter
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [ ]:
# 내 버전
# 성인 인지 아닌지
import numpy as np


def adult(row):
    # 19세 이상이면 1, 19세 미만이면 0, 아니면 nan으로 리턴
    if row["Age"] >= 19 :
        return 1
    elif row["Age"] < 19 :
        return 0
    else:
        return np.nan

df1 = df.copy()

In [ ]:
df1["adult_yn"] = df1.apply(adult, axis=1)
df1.head()

In [ ]:
# 강사님 버전
# 성인 인지 아닌지

import numpy as np

def adult(age): # 시리즈형태로 들어오는 것이 아니라 하나하나씩 들어오는 거라 파라미터는 스칼라값을 가지게 됨
  # 19세 이상이면 1, 19세 미만이면 0, 아니면 nan으로 리턴
  if age >= 19:
    return 1
  elif age < 19:
    return 0
  else:
    return np.nan

df1['adult_yn'] = df1['Age'].apply(adult) # 무조건 age만 가져오는 거기 때문에 axis도 필요 없어짐
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,pclass_sibsp_filter,adult_yn
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,1.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,1.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1.0

In [ ]:
# lambda 형식으로 만들기
df1['pclass_sibsp_lambda'] = df1.apply(
    lambda row : 1 if row['Pclass'] == 1 and row["SibSp"] == 1 else 0,
    axis=1
)

df1.head()

# 나중에 재사용할때는 def을 쓰는게 더 좋다

# lambda는 파라미터에 딱 한번 들어갈 정도(재사용하지 않는)면 쓰는 것이 좋다. 가벼운 함수

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,pclass_sibsp_filter,adult_yn,pclass_sibsp_lambda
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,1.0,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,1.0,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1.0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,1.0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1.0,0

# map 함수
- 값을 특정 값으로 치환할 때 사용한다.

apply는 기능을 만드는 거라면 (기능의 실행변화),   map은 mapping을 하는 값의 변환 값을 치환할 때 사용

apply가 더 크게 쓸 수 있음 map은 로직이 들어가는 순간 못씀

map으로 하는 거는 apply로도 쓸 수 있다.

In [ ]:
# map -> dict
gender_map = {
    "male": "남자",
    "female": "여자"
}

df1['Sex_kr'] = df1['Sex'].map(gender_map)
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,pclass_sibsp_filter,adult_yn,pclass_sibsp_lambda,Sex_kr
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,1.0,0,남자
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,1.0,1,여자
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1.0,0,여자
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,1.0,1,여자
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1.0,0,남자

# 문자열 다루기⭐️

|메소드|설명|
|:--|:--|
|`.str.contains(문자열)`|문자열을 포함하고 있는지 유무|
|`.str.replace(기존문자열, 대치문자열)`|문자열 대치|
|`.str.split(문자열, expand=True/False, n=개수)`|특정 문자열을 기준으로 쪼개기|
|`.str.lower()`|소문자로 바꾸기|
|`.str.upper()`|대문자로 바꾸기|

In [ ]:
# 예를 들어 이름에 'Miss'가 들어간 사람만 찾기
df2 = df.copy()

# 시리즈에서 담고 있는 문자열에 접근하려면 .str를 붙여서 사용해야함
# 시리즈에 있는 형태가 문자열이라고 바로 사용하면 안됨 반드시 .str사용하기
miss_mask = df2["Name"].str.contains("Miss") # mask로도 사용가능
df2.loc[miss_mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df2["Name"] = df2["Name"].str.replace(",", "😀")
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Braund😀 Mr. Owen Harris,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,Cumings😀 Mrs. John Bradley (Florence Briggs Th...,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Heikkinen😀 Miss. Laina,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,Futrelle😀 Mrs. Jacques Heath (Lily May Peel),female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Allen😀 Mr. William Henry,male,35.0,0,0,373450,8.0500,NaN,S