<a href="https://colab.research.google.com/github/leesolhahaha/Data_Analysis_with_Python/blob/main/09_%5BPandas%5D_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EA%B0%80%EA%B3%B5%2C_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EA%B2%B0%ED%95%A9_concat%2C_merge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df1 = pd.read_csv("./data/korean-idol.csv")
df2 = pd.read_csv("./data/korean-idol-2.csv")

In [ ]:
df1.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [ ]:
df2.head()

     이름    연봉  가족수
0    지민  3000    3
1  지드래곤  3500    3
2  강다니엘  3200    4
3     뷔  3050    4
4    화사  4300    3

# Concat

## row 기준 합치기
- 행 인덱스를 기준으로 합치기

In [ ]:
df1_copy = df1.copy()

In [ ]:
df1_concat = pd.concat([df1, df1_copy], axis=0) # axis=0이니까 아래쪽으로 데이터가 늘어 남 위에서 아래로 합쳐지는 것이기 때문에 columns의 이름이 같아야함
df1_concat

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [ ]:
# 인덱스 재 설정
df1_concat.reset_index(drop=True) # drop=True를 사용하면 인덱스가 재 세팅 됨

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
15    지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
16  지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
17  강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
18     뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
19    화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
20    정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
21    민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
22    소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
23     진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
24   하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
25    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
26   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
27    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
28    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
29    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

## 열 기준 합치기
- concat에서 axis=1로 설정

In [ ]:
df2

      이름    연봉  가족수
0     지민  3000    3
1   지드래곤  3500    3
2   강다니엘  3200    4
3      뷔  3050    4
4     화사  4300    3
5     정국  2900    5
6     민현  3400    6
7     소연  4500    5
8      진  4200    4
9    하성운  4300    4
10    태연  3700    3
11   차은우  3850    5
12    백호  3900    4
13    JR  4100    3
14    슈가  4150    3

In [ ]:
pd.concat([df1, df2], axis=1) # 밑으로 합치는게 아니라 columns를 늘릴 거기 때문에 axis=1로 만들어야함

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수    이름    연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260    지민  3000    3
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947  지드래곤  3500    3
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745  강다니엘  3200    4
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501     뷔  3050    4
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928    화사  4300    3
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335    정국  2900    5
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792    민현  3400    6
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615    소연  4500    5
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308     진  4200    4
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489   하성운  4300    4
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661    태연  3700    3
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027   차은우  3850    5
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654    백호  3900    4
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137    JR  4100    3
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442    슈가  4150    3

In [ ]:
df3 = df2.drop([3, 5])
df3

      이름    연봉  가족수
0     지민  3000    3
1   지드래곤  3500    3
2   강다니엘  3200    4
4     화사  4300    3
6     민현  3400    6
7     소연  4500    5
8      진  4200    4
9    하성운  4300    4
10    태연  3700    3
11   차은우  3850    5
12    백호  3900    4
13    JR  4100    3
14    슈가  4150    3

In [ ]:
pd.concat([df1, df3], axis=1) # 없는 부분은 nan값으로 나오게 됨

,이름,그룹,소속사,성별,생년월일,키,혈액형,브랜드평판지수,이름,연봉,가족수
0,지민,방탄소년단,빅히트,남자,1995-10-13,173.6,A,10523260,지민,3000.0,3.0
1,지드래곤,빅뱅,YG,남자,1988-08-18,177.0,A,9916947,지드래곤,3500.0,3.0
2,강다니엘,NaN,커넥트,남자,1996-12-10,180.0,A,8273745,강다니엘,3200.0,4.0
3,뷔,방탄소년단,빅히트,남자,1995-12-30,178.0,AB,8073501,NaN,NaN,NaN
4,화사,마마무,RBW,여자,1995-07-23,162.1,A,7650928,화사,4300.0,3.0
5,정국,방탄소년단,빅히트,남자,1997-09-01,178.0,A,5208335,NaN,NaN,NaN
6,민현,뉴이스트,플레디스,남자,1995-08-09,182.3,O,4989792,민현,3400.0,6.0
7,소연,아이들,큐브,여자,1998-08-26,NaN,B,4668615,소연,4500.0,5.0
8,진,방탄소년단,빅히트,남자,1992-12-04,179.2,O,4570308,진,4200.0,4.0
9,하성운,핫샷,스타크루이엔티,남자,1994-03-22,167.1,A,4036489,하성운,4300.0,4.0
10,태연,소녀시대,SM,여자,1989-03-09,NaN,A,3918661,태연,3700.0,3.0
11,차은우,아스트로,판타지오,남자,1997-03-30,183.0,B,3506027,차은우,3850.0,5.0
12,백호,뉴이스트,플레디스,남자,1995-07-21,175.0,AB,3301654,백호,3900.0,4.0
13,JR,뉴이스트,플레디스,남자,1995-06-08,176.0,O,3274137,JR,4100.0,3.0
14,슈가,방탄소년단,빅히트,남자,1993-03-09,174.0,O,2925442,슈가,4150.0,3.0

In [ ]:
# 잘못된 합치기 예시
df4 = df3.copy()
df4 = df4.reset_index(drop=True)
df4

      이름    연봉  가족수
0     지민  3000    3
1   지드래곤  3500    3
2   강다니엘  3200    4
3     화사  4300    3
4     민현  3400    6
5     소연  4500    5
6      진  4200    4
7    하성운  4300    4
8     태연  3700    3
9    차은우  3850    5
10    백호  3900    4
11    JR  4100    3
12    슈가  4150    3

In [ ]:
pd.concat([df1, df4], axis=1) # 데이터의 짝이 안맞게 값이 달라지게 되므로 인덱스 세팅은 신중하게 해야함

,이름,그룹,소속사,성별,생년월일,키,혈액형,브랜드평판지수,이름,연봉,가족수
0,지민,방탄소년단,빅히트,남자,1995-10-13,173.6,A,10523260,지민,3000.0,3.0
1,지드래곤,빅뱅,YG,남자,1988-08-18,177.0,A,9916947,지드래곤,3500.0,3.0
2,강다니엘,NaN,커넥트,남자,1996-12-10,180.0,A,8273745,강다니엘,3200.0,4.0
3,뷔,방탄소년단,빅히트,남자,1995-12-30,178.0,AB,8073501,화사,4300.0,3.0
4,화사,마마무,RBW,여자,1995-07-23,162.1,A,7650928,민현,3400.0,6.0
5,정국,방탄소년단,빅히트,남자,1997-09-01,178.0,A,5208335,소연,4500.0,5.0
6,민현,뉴이스트,플레디스,남자,1995-08-09,182.3,O,4989792,진,4200.0,4.0
7,소연,아이들,큐브,여자,1998-08-26,NaN,B,4668615,하성운,4300.0,4.0
8,진,방탄소년단,빅히트,남자,1992-12-04,179.2,O,4570308,태연,3700.0,3.0
9,하성운,핫샷,스타크루이엔티,남자,1994-03-22,167.1,A,4036489,차은우,3850.0,5.0
10,태연,소녀시대,SM,여자,1989-03-09,NaN,A,3918661,백호,3900.0,4.0
11,차은우,아스트로,판타지오,남자,1997-03-30,183.0,B,3506027,JR,4100.0,3.0
12,백호,뉴이스트,플레디스,남자,1995-07-21,175.0,AB,3301654,슈가,4150.0,3.0
13,JR,뉴이스트,플레디스,남자,1995-06-08,176.0,O,3274137,NaN,NaN,NaN
14,슈가,방탄소년단,빅히트,남자,1993-03-09,174.0,O,2925442,NaN,NaN,NaN

# merge
- `concat`과 `merge`는 단순하게 합쳐지는 목적 또는 특정 기준(`index`)으로 합치느냐에 따라서 용도가 달라집니다.
- `concat` : `row`나 `column` 기준으로 단순하게 이어 붙이기
- `merge` : 특정한 고유 키(`unique id`) 값을 기준으로 **병합**

**`pd.merge(left, right, on='기준 컬럼', how='left')`**
- `left`, `right` : 병합할 두 DataFrame
- `on` : 병합의 기준이 되는 컬럼의 이름
- `how` : `left, right, inner, outer` 4가지 병합방식 설정

In [ ]:
df2_right = df2.drop([1, 3, 5, 7, 9], axis=0)
df2_right = df2_right.reset_index(drop=True)
df2_right

     이름    연봉  가족수
0    지민  3000    3
1  강다니엘  3200    4
2    화사  4300    3
3    민현  3400    6
4     진  4200    4
5    태연  3700    3
6   차은우  3850    5
7    백호  3900    4
8    JR  4100    3
9    슈가  4150    3

In [ ]:
df1.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [ ]:
pd.concat([df1, df2_right], axis=1) # drop된 것 때문에 합쳐진 값이 이상한 것을 알 수 있다

,이름,그룹,소속사,성별,생년월일,키,혈액형,브랜드평판지수,이름,연봉,가족수
0,지민,방탄소년단,빅히트,남자,1995-10-13,173.6,A,10523260,지민,3000.0,3.0
1,지드래곤,빅뱅,YG,남자,1988-08-18,177.0,A,9916947,강다니엘,3200.0,4.0
2,강다니엘,NaN,커넥트,남자,1996-12-10,180.0,A,8273745,화사,4300.0,3.0
3,뷔,방탄소년단,빅히트,남자,1995-12-30,178.0,AB,8073501,민현,3400.0,6.0
4,화사,마마무,RBW,여자,1995-07-23,162.1,A,7650928,진,4200.0,4.0
5,정국,방탄소년단,빅히트,남자,1997-09-01,178.0,A,5208335,태연,3700.0,3.0
6,민현,뉴이스트,플레디스,남자,1995-08-09,182.3,O,4989792,차은우,3850.0,5.0
7,소연,아이들,큐브,여자,1998-08-26,NaN,B,4668615,백호,3900.0,4.0
8,진,방탄소년단,빅히트,남자,1992-12-04,179.2,O,4570308,JR,4100.0,3.0
9,하성운,핫샷,스타크루이엔티,남자,1994-03-22,167.1,A,4036489,슈가,4150.0,3.0
10,태연,소녀시대,SM,여자,1989-03-09,NaN,A,3918661,NaN,NaN,NaN
11,차은우,아스트로,판타지오,남자,1997-03-30,183.0,B,3506027,NaN,NaN,NaN
12,백호,뉴이스트,플레디스,남자,1995-07-21,175.0,AB,3301654,NaN,NaN,NaN
13,JR,뉴이스트,플레디스,남자,1995-06-08,176.0,O,3274137,NaN,NaN,NaN
14,슈가,방탄소년단,빅히트,남자,1993-03-09,174.0,O,2925442,NaN,NaN,NaN

In [ ]:
pd.merge(
    df1,
    df2_right,
    on='이름',
    how='left' # left에 위치한 df1이 기준이 된다. 기준이 된 데이터 프레임은 데이터의 삭제가 일어나지 않는다.
)

      이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수      연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260  3000.0  3.0
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947     NaN  NaN
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745  3200.0  4.0
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501     NaN  NaN
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928  4300.0  3.0
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335     NaN  NaN
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792  3400.0  6.0
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615     NaN  NaN
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308  4200.0  4.0
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489     NaN  NaN
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661  3700.0  3.0
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027  3850.0  5.0
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654  3900.0  4.0
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137  4100.0  3.0
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442  4150.0  3.0

In [ ]:
pd.merge(
    df1,
    df2_right,
    on='이름',
    how='right' # right에 위치한 df1이 기준이 된다. 오른쪽 데이터가 기준이 되기 때문에 오른쪽 데이터에 맞춰져서 왼쪽에디터에 변경이 일어났다.
)

     이름     그룹   소속사  성별        생년월일      키 혈액형   브랜드평판지수    연봉  가족수
0    지민  방탄소년단   빅히트  남자  1995-10-13  173.6   A  10523260  3000    3
1  강다니엘    NaN   커넥트  남자  1996-12-10  180.0   A   8273745  3200    4
2    화사    마마무   RBW  여자  1995-07-23  162.1   A   7650928  4300    3
3    민현   뉴이스트  플레디스  남자  1995-08-09  182.3   O   4989792  3400    6
4     진  방탄소년단   빅히트  남자  1992-12-04  179.2   O   4570308  4200    4
5    태연   소녀시대    SM  여자  1989-03-09    NaN   A   3918661  3700    3
6   차은우   아스트로  판타지오  남자  1997-03-30  183.0   B   3506027  3850    5
7    백호   뉴이스트  플레디스  남자  1995-07-21  175.0  AB   3301654  3900    4
8    JR   뉴이스트  플레디스  남자  1995-06-08  176.0   O   3274137  4100    3
9    슈가  방탄소년단   빅히트  남자  1993-03-09  174.0   O   2925442  4150    3

# inner, outer 방식
- `inner` : 두 데이터 프레임에 **모두** 키값이 존재하는 경우 병합
- `outer` : 하나의 데이터 프레임에 키값이 존재하는 경우 모두 병합
  - 없는 값은 NaN값으로 대입

교집합, 합집합

In [ ]:
df1_left = df1.drop([1, 2, 6, 8])
df1_left

     이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
3     뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5    정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
7    소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
9   하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10   태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11  차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12   백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13   JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14   슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [ ]:
pd.merge(df1_left, df2_right, on="이름", how='inner')
# 겹치는 것만 살아남게 됨 교집합(inner)

    이름     그룹   소속사  성별        생년월일      키 혈액형   브랜드평판지수    연봉  가족수
0   지민  방탄소년단   빅히트  남자  1995-10-13  173.6   A  10523260  3000    3
1   화사    마마무   RBW  여자  1995-07-23  162.1   A   7650928  4300    3
2   태연   소녀시대    SM  여자  1989-03-09    NaN   A   3918661  3700    3
3  차은우   아스트로  판타지오  남자  1997-03-30  183.0   B   3506027  3850    5
4   백호   뉴이스트  플레디스  남자  1995-07-21  175.0  AB   3301654  3900    4
5   JR   뉴이스트  플레디스  남자  1995-06-08  176.0   O   3274137  4100    3
6   슈가  방탄소년단   빅히트  남자  1993-03-09  174.0   O   2925442  4150    3

In [ ]:
pd.merge(df1_left, df2_right, on="이름", how='outer')
# 양쪽의 데이터가 모조리 살아남게 됨 합집합 (outer) 없는 부분은 NaN값으로 채워짐

      이름     그룹      소속사   성별        생년월일      키  혈액형     브랜드평판지수      연봉  가족수
0     JR   뉴이스트     플레디스   남자  1995-06-08  176.0    O   3274137.0  4100.0  3.0
1   강다니엘    NaN      NaN  NaN         NaN    NaN  NaN         NaN  3200.0  4.0
2     민현    NaN      NaN  NaN         NaN    NaN  NaN         NaN  3400.0  6.0
3     백호   뉴이스트     플레디스   남자  1995-07-21  175.0   AB   3301654.0  3900.0  4.0
4      뷔  방탄소년단      빅히트   남자  1995-12-30  178.0   AB   8073501.0     NaN  NaN
5     소연    아이들       큐브   여자  1998-08-26    NaN    B   4668615.0     NaN  NaN
6     슈가  방탄소년단      빅히트   남자  1993-03-09  174.0    O   2925442.0  4150.0  3.0
7     정국  방탄소년단      빅히트   남자  1997-09-01  178.0    A   5208335.0     NaN  NaN
8     지민  방탄소년단      빅히트   남자  1995-10-13  173.6    A  10523260.0  3000.0  3.0
9      진    NaN      NaN  NaN         NaN    NaN  NaN         NaN  4200.0  4.0
10   차은우   아스트로     판타지오   남자  1997-03-30  183.0    B   3506027.0  3850.0  5.0
11    태연   소녀시대       SM   여자  1989-03-09    NaN    A   3918661.0  3700.0  3.0
12   하성운     핫샷  스타크루이엔티   남자  1994-03-22  167.1    A   4036489.0     NaN  NaN
13    화사    마마무      RBW   여자  1995-07-23  162.1    A   7650928.0  4300.0  3.0